version: '3.8'

services:
  nightingale:
    image: ghcr.io/rajanagori/nightingale:arm64
    container_name: nightingale
    command: ["ttyd", "-p", "7681", "bash"]
    ports:
      - "8080:7681"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - nightingale
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    restart: unless-stopped