# Pulling the base image
FROM kalilinux/kali:latest

#Installing Depen
RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get install -y python3-pip python3-dev &&\
    cd /usr/local/bin &&\
    ln -s /usr/bin/python3 python &&\
    pip3 install --upgrade pip &&\
    git \
    ruby \
    ruby-dev \
    libcurl4-openssl-dev \
    make

