# Pulling the base image
FROM kalilinux/kali:latest

# Installing Dependencies for kali linux environment
RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get install -y python3-pip python3-dev &&\
    cd /usr/local/bin &&\
    ln -s /usr/bin/python3 python &&\
    pip3 install --upgrade pip
    
RUN apt-get install -y git \
    ruby \
    ruby-dev \
    libcurl4-openssl-dev \
    make 

#Working Directory of tools
RUN mkdir tool
# Installing WP-Scan 
RUN git clone https://github.com/wpscanteam/wpscan.git \
    cd wpscan \
    gem install bundler && \
    bundle install --without test

# Installing SqlMap
RUN 
https://github.com/sqlmapproject/sqlmap.git \
   cd sqlmap


