name: Build & Push Docker Images

# Trigger on pushes to main (or master) and manual dispatch
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE: ${{ env.REGISTRY }}/rajanagori/nightingale_backend:amd64
  FRONTEND_IMAGE: ${{ env.REGISTRY }}/rajanagori/nightingale_frontend:amd64

jobs:
  # Job 1: Build & push the Go backend image
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (for cross-builds)
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.USERNAME }}
          password: ${{ secrets.TOKEN }}

      - name: Build & push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./gui/go_backend
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE }}

  # Job 2: Build & push the Next.js frontend image
  build-frontend:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (for cross-builds)
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./gui/feature-UI-one
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE }}